eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
        defaultZone: http://localhost:8761/eureka/
   instance:
     hostname: localhost

amount-limit:
   minimum: 1
   maximum: 99999
